# Generated by Django 4.2 on 2026-06-24 23:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0001_initial'),
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocodeusage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_code_usages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promocode',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='promo_codes', to='catalog.category'),
        ),
        migrations.AddConstraint(
            model_name='promocodeusage',
            constraint=models.UniqueConstraint(fields=('user', 'promo_code'), name='unique_user_promo_code_usage'),
        ),
    ]
